### ISSUE TITLE
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native-tab-bar-interaction` from `/Users/Ton/Desktop/Internship/navigationDemo/App1.js`: Module `react-native-tab-bar-interaction` does not exist in the Haste module map  This might be related to https://github.com/facebook/react-native/issues/4968 

### ISSUE THREAD

**Issue by tontact** [Mindinventory/react-native-tabbar-interaction#10]
I have this problem anybody can solve it.( My react native version 3) or this library cannot support in version 3

**Comment by bhavika162** [comment]
@tontact, Its might be issue having to import the plugin, please use below line to import 'react-native-tab-bar-interaction'

import TabBar from '@mindinventory/react-native-tab-bar-interaction'

**Comment by tontact** [comment]
Yes, I already use this import (import TabBar from '@mindinventory/react-native-tab-bar-interaction')  but I still have this problem. can you give another solution ?

**Comment by chazzaoui** [comment]
I am experiencing the same issue.
After installing it gives the error as described above. 

tried deleting the node modules and reinstalling, and restarting the simulator and bundler.
Noting seems to work

**Comment by walter-grace** [comment]
I am getting the same error as well, I even tried using expo install~

**Comment by longnk-1447** [comment]
check my pull [16](https://github.com/Mindinventory/react-native-tabbar-interaction/pull/16)

**Comment by md-one** [comment]
did anyone find solution for this problem? and if not do anyone have alternative react native tabbar?

**Comment by akashmi** [comment]
Upgraded the new version with reported issues fixes and enhancements.
We always appreciate suggestions, enhancement or PR with new features from the community. 
Please try the latest version 2.1.2.
