### ISSUE TITLE
Use SVG as tab icons

### ISSUE THREAD

**Issue by okechukwu0127** [Mindinventory/react-native-tabbar-interaction#11]
This package is really slicky and nice as i was able to install it and use it.
The truth is, what attracted me was the transitions of the SVG images been used as the Tab Icons.

But now, i am stuck with using a still image as the tab icons.

So my question is how can i use an SVG image as the tab icons so that my icon transition would be complete as we have in the demo image design.

**Comment by akashmi** [comment]
Upgraded the new version with reported issues fixes and enhancements.
We always appreciate suggestions, enhancement or PR with new features from the community. 
Please try the latest version 2.1.2.
Now you can use your own view as activeTab and inactiveTab.
