### ISSUE TITLE
Add typings for TypeScript

### ISSUE THREAD

**Issue by martin-braun** [Mindinventory/react-native-tabbar-interaction#12]
Please, add typings for this component to use it with TypeScript.

**Comment by longnk-1447** [comment]
@l-Marty-l you can provide template you want add typeScript?

**Comment by akashmi** [comment]
@martin-braun we are working on new updates and will give TypeScript support in the next version.

**Comment by akashmi** [comment]
@martin-braun 
Now this library support typescript from version 2.2.0.
