### ISSUE TITLE
Tabs get fixed when opening keyboard

### ISSUE THREAD

**Issue by gustavofalcao1** [Mindinventory/react-native-tabbar-interaction#17]
I have a screen with inputs, when I type something Tabs on with the keyboard, I'm trying to keep it down, but I still can't

**Comment by longnk-1447** [comment]
@gustavofalcao1 Can purpose a template?

**Comment by akashmi** [comment]
Thanks for using this library. We have released a new version with enhancements. Please try and if you still getting the same issue feel free to raise an issue.
