### ISSUE TITLE
Getting Module Parse Failure for this 

### ISSUE THREAD

**Issue by raoghuge** [Mindinventory/react-native-tabbar-interaction#27]
Getting following error : 
**~node_modules/@mindinventory/react-native-tab-bar-interaction/TabBar.js 29:12**

Module parse failed: Unexpected token (29:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|         return (
>             <View style={{flex: 1}}>
|                 {child}
|             </View>

**Comment by akashmi** [comment]
Upgraded the new version with reported issues fixes and enhancements.
We always appreciate suggestions and enhancement from the community.
Please try the latest version.
