### ISSUE TITLE
No valid versions available for react-native-tab-bar-interaction

### ISSUE THREAD

**Issue by pavlea** [Mindinventory/react-native-tabbar-interaction#3]
A workaround is to install it like `npm install https://github.com/Mindinventory/react-native-tabbar-interaction.git`, but regular npm install is not working. It throws `No valid versions available for react-native-tab-bar-interaction `

**Comment by malvikiran** [comment]
Hello @pavlea ,

Please try this command: npm i mindinventory/react-native-tab-bar-interaction

Let me know, is it working or not?
