### ISSUE TITLE
Missing " in documentation

### ISSUE THREAD

**Issue by The-CodeNinja** [Mindinventory/react-native-tabbar-interaction#30]
<TabBar bgNavBar="white" bgNavBarSelector="white" stroke=**"skyblue**>
          here a " is missing after skyblue
          
          don't know if this is the right place to submit such an issue. First timer here!

**Comment by akashmi** [comment]
@The-CodeNinja Yes, It's the right place to raise issues or provide suggestions.
we are upgrading lib and will launch the new version with new suggestions from the community.

**Comment by akashmi** [comment]
Upgraded the new version with reported issues fixes and enhancements.
We always appreciate suggestions and enhancement from the community.
Please try the latest version.
