### ISSUE TITLE
Custom Screen

### ISSUE THREAD

**Issue by Itesh12** [Mindinventory/react-native-tabbar-interaction#34]
How can i goto custom screen if i select and tab.

**Comment by chiragramimi** [comment]
@Itesh12, You can use  `onTabChange` prop to redirect to the custom screen. please look at the below snippet for it.

```
  <Tabbar
    tabs={tabs}
    tabBarContainerBackground='#6699ff'
    tabBarBackground='#fff'
    activeTabBackground='#6699ff'
    labelStyle={{ color: '#4d4d4d', fontWeight: '600', fontSize: 11 }}
    onTabChange={() => console.log('Tab changed')}
  />
```

let me know if you still haven't found out it.

**Comment by chiragramimi** [comment]
> How can i goto custom screen if i select and tab.

@Itesh12, You can use onTabChange prop to redirect to the custom screen. please look at the below snippet for it.

  <Tabbar
    tabs={tabs}
    tabBarContainerBackground='#6699ff'
    tabBarBackground='#fff'
    activeTabBackground='#6699ff'
    labelStyle={{ color: '#4d4d4d', fontWeight: '600', fontSize: 11 }}
    onTabChange={() => console.log('Tab changed')}
  />
let me know if you still haven't found out it.
