### ISSUE TITLE
Failed to compile, because of not resolving path

### ISSUE THREAD

**Issue by trwxo** [Mindinventory/react-native-tabbar-interaction#35]
If I want to compile it, I always get message:
-------------------------------------------------------
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve './Tabbar/TabBar' in '/var/www/.../node_modules/@mindinventory/react-native-tab-bar-interaction'
-------------------------------------------------------
Is there something wrong with the paths?

**Comment by chiragramimi** [comment]
@trwxo, Thanks for the addressing issue.

We update the installation step in the documentation. So please follow the updated installation step. 

Before the installation please `remove lib form node_modules` and re-install it.

Please let us know, in case you face the issue/problem yet again.

**Comment by trwxo** [comment]
My check was better, but major problem was still the same.
I installed react again via the create-react-app and followed your description, changed the "metro.config.js" in the folder "/node_modules/react-native/template" and created the declarations.d.ts - one warning was gone with it, but the major effect is still the same:
------------------------------------------------------------------
ERROR in ./node_modules/@mindinventory/react-native-tab-bar-interaction/index.ts 1:0-37
Module not found: Error: Can't resolve './Tabbar/TabBar' in '/var/www...
------------------------------------------------------------------
I also did the "npm remove lib form node_modules" before - did I miss something important?
![image](https://user-images.githubusercontent.com/96752360/147614782-59aafa38-1788-4378-a521-305ebca64b90.png)

**Comment by trwxo** [comment]
> Please let us know, in case you face the issue/problem yet again.

Yes, documentation still not work (see screenshot)

**Comment by akashmi** [comment]
> > Please let us know, in case you face the issue/problem yet again.
> 
> Yes, documentation still not work (see screenshot)

@trwxo seems like you are working on React App, and this lib is only for Reactnative apps.
