### ISSUE TITLE
Types error when using with typescript/tsx

### ISSUE THREAD

**Issue by b-tiwari** [Mindinventory/react-native-tabbar-interaction#37]
I am getting below errors when using this awesome package with typescript.

![1](https://user-images.githubusercontent.com/13605214/147872910-0c96ad6a-5db7-4678-aa6a-5866798f996f.png)

I have followed the installation instructions as specified on the [package's github page ](https://github.com/Mindinventory/react-native-tabbar-interaction)

Even though I do have `skipLibCheck: true` in tsconfig's compilerOptions and also have 'node_moduels in the `excluded` list of tsconfig, not sure why getting these errors, most of these are for the type discrepancies in `node_modules/@mindinventory/react-native-tab-bar-interaction` folder.

![2](https://user-images.githubusercontent.com/13605214/147872917-74c9b5b2-43a8-48bd-8a27-1466e284e877.png)

Please help

**Comment by akashmi** [comment]
@b-tiwari 
Please try now with the latest version of react-native-tabbar-interaction lib. we have added typescript support to this lib.
Feel free to reopen or create a new issue if you get the same issue.

**Comment by b-tiwari** [comment]
Thanks for the reply.

yes, I had the most recent version with typescript type defs. I am guessing, the error could be because I have `strict` and `noImplicitAny` set to `true` in my `tsconfig` which you might have set to false in yours.

I moved on to another library for tabs, not using this any longer. But you may still want to look into the issue.
