### ISSUE TITLE
In Android keyboard shifts the tab bar up.

### ISSUE THREAD

**Issue by reactnativedevelopers** [Mindinventory/react-native-tabbar-interaction#4]
Hi,

In Android, I am facing an issue. I have multiple TextInputs. When I click on any of the TextInput, the keyboard shifts the tab bar. I am attaching the screenshots.

![screen shot 2018-09-24 at 12 32 45 am](https://user-images.githubusercontent.com/40722546/45931880-f1a3b100-bf91-11e8-97a9-095663c2fe4c.png)

![screen shot 2018-09-24 at 12 33 12 am](https://user-images.githubusercontent.com/40722546/45931882-fa948280-bf91-11e8-8b01-d200b9aaf733.png)

Please help.

Thanks :)

**Comment by bhavika162** [comment]
@reactnativedevelopers,

Config your AndroidManifest.xml with below line. 
android:windowSoftInputMode="stateAlwaysHidden|adjustPan" (add this line inside <activity.. /> section. )
