### ISSUE TITLE
How can we change transition speed ?

### ISSUE THREAD

**Issue by Satishpethani92** [Mindinventory/react-native-tabbar-interaction#41]
Hello 
Good job!
Hoe can we change speed of transition? 
If this is not already added in the functionality then please add it.

And also i have one more issue in the library like when application comes from background that time icon is not display.

**Comment by akashmi** [comment]
Hi, @Satishpethani92 Thanks for using this lib and providing your feedback.
sure in the next version, we will add an option to change transition duration.

> And also i have one more issue in the library like when application comes from background that time icon is not display.
It will be helpful if you can provide a video for this case/issue.

**Comment by akashmi** [comment]
@Satishpethani92  please try the latest version 2.2.2 for your request. we have added the option to change the transition duration.
https://github.com/Mindinventory/react-native-tabbar-interaction#tabbar

**Comment by akashmi** [comment]
> And also i have one more issue in the library like when application comes from background that time icon is not display.

We tried to reproduce this issue. it seems working fine. 
If you are still facing same issue please create new issue with more details/video.
