### ISSUE TITLE
run in android not work like demo 

### ISSUE THREAD

**Issue by DatDoan20** [Mindinventory/react-native-tabbar-interaction#43]
Hi. Sir.
Could you check lib run in Android. I run in Android and curve of tabbar not like demo, Could you give me code draw curve like demo, please
![image](https://user-images.githubusercontent.com/92727122/167396277-9502ff1c-8999-4ea0-a14c-188bf1b482a1.png)

**Comment by akashmi** [comment]
@DatDoan20 
Please try the new version `2.2.3`. if you are getting the same issue with the newer version create a new issue.
