### ISSUE TITLE
wrong position in rtl 

### ISSUE THREAD

**Issue by AkaE41** [Mindinventory/react-native-tabbar-interaction#44]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-18 at 15 01 17](https://user-images.githubusercontent.com/92668492/169044630-19e9994d-1d62-406a-ba42-53f1ebe497f1.png)

I just make the width 200 to produce the issue and you can understand what I am take about

**Comment by akashmi** [comment]
@AkaE41 we have added RTL support in the new version `2.2.3`.

**Comment by AkaE41** [comment]
@akashmi  thanks a lot for that
