### ISSUE TITLE
this doesn't look like the animation...

### ISSUE THREAD

**Issue by digitalcraft** [Mindinventory/react-native-tabbar-interaction#46]

**Comment by chiragramimi** [comment]
@digitalcraft 

I understand your concern. Could you please point out the specific aspects that you feel are not matching the animation? This will help us address those discrepancies.

**Comment by digitalcraft** [comment]
the design is super premium, and the example is well... "different".

**Comment by chiragramimi** [comment]
@digitalcraft,

 I understand your point. The design was meant to have a premium touch, but the current example doesn't quite match. We can use Component props like activeIcon and integrate Lottie animations to better align with the desired feel.

We'll be focusing on refining the example to closely match the intended design. By utilizing techniques like activeIcon and integrating Lottie animations, we aim to achieve an outcome that visually aligns with the desired image.

**Comment by chiragramimi** [comment]
@digitalcraft,

You can find the solution in the [feat/bottom_tab_bar](https://github.com/Mindinventory/react-native-tabbar-interaction/tree/feat/bottom_tab_bar) branch. I'm planning to close this ticket for now, and we'll merge these changes into the main branch.
