### ISSUE TITLE
Already added three tab items but still returns an Error:  "Error: Three tab should be work"

### ISSUE THREAD

**Issue by hotmarycorleone** [Mindinventory/react-native-tabbar-interaction#5]
import React, { Component } from 'react';
import {View} from 'react-native';
import { Container, Header, Content, Card, CardItem, Text, Body } from 'native-base';
import TabBar from "react-native-tab-bar-interaction";

export default class App extends Component {
  render() {
    return (
      <TabBar>

        <TabBar.Item
         icon={require('./images/jeepney.png')}
         selectedIcon={require('./images/noimage.png')}
         title="Tab1"
         screenBackgroundColor={{ backgroundColor: '#008080' }}
     >
        <View>
        <Text>Tab First</Text>
        </View>
        </TabBar.Item>

        <TabBar.Item
         icon={require('./images/parking.png')}
         selectedIcon={require('./images/noimage.png')}
         title="Tab2"
         screenBackgroundColor={{ backgroundColor: '#F08080' }}
     >
        <View>
        <Text>Tab Second</Text>
        </View>
        </TabBar.Item>

        <TabBar.Item
         icon={require('./images/shuttle.png')}
         selectedIcon={require('./images/noimage.png')}
         title="Tab3"
         screenBackgroundColor={{ backgroundColor: '#485d72' }}
     >
         <View>
         <Text>Tab Third</Text>
         </View>
         </TabBar.Item>

        

         </TabBar>

    );
  }
}

**Comment by Miladvp** [comment]
Hi 
you forgot to write your three tabs in TabBar 
`import TabBar from "react-native-tab-bar-interaction";
class example extends Component{
    render( ) {
      return ( 
           <TabBar>
               <TabBar.Item><tabBar.Item/>
               <TabBar.Item><tabBar.Item/>
               <TabBar.Item><tabBar.Item/>
          <TabBar/>
      )
  }
}`
