### ISSUE TITLE
Already added dependency but still error

### ISSUE THREAD

**Issue by nancycssjockey** [Mindinventory/react-native-tabbar-interaction#6]
I have added dependency using  

npm i mindinventory/react-native-tab-bar-interaction

It throws error: bundling failed: Error: Unable to resolve module `react-native-tab-bar-interaction`
 Module `react-native-tab-bar-interaction` does not exist in the Haste module map

**Comment by Lahkimomar** [comment]
Same for me!

**Comment by Eesssn** [comment]
@nancycssjockey @Lahkimomar you should add "@mindinventory/react-native-tab-bar-interaction" instead of "react-native-tab-bar-interaction"

**Comment by adamalexander** [comment]
Anybody got this working??

**Comment by bhavika162** [comment]
@nancycssjockey 
Please try with below command.

npm i @mindinventory/react-native-tab-bar-interaction

**Comment by hossein92** [comment]
@nancycssjockey : you should use the `"@mindinventory/react-native-tab-bar-interaction"` and  svg library in your project .
please check library link : [svg libraty](https://github.com/react-native-community/react-native-svg)

**Comment by tontact** [comment]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native-tab-bar-interaction` from `/Users/Ton/Desktop/Internship/navigationDemo/App1.js`: Module `react-native-tab-bar-interaction` does not exist in the Haste module map

I have this problem anybody can solve it.( My react native version 3) or this library cannot support in version 3
