### ISSUE TITLE
how we can add more than 3 tab ,is there any alternate options for it?

### ISSUE THREAD

**Issue by vyasishanatc194** [Mindinventory/react-native-tabbar-interaction#7]
I have 5 tab, i want to use this library for tab. but i'm not able add more than 3 tab.
showing error like this " Three tab should be work."

**Comment by bhavika162** [comment]
Hello,
This library is for three tab only, soon we will upgrade the library with
five tab.

**Comment by malvikiran** [comment]
We will upgrade in next version.
