### ISSUE TITLE
5 item tabbar

### ISSUE THREAD

**Issue by Eesssn** [Mindinventory/react-native-tabbar-interaction#8]
hi
did u solve add 5 item to menu?
that for responsibility

**Comment by malvikiran** [comment]
It will be available in next version.

**Comment by Malikkhoja** [comment]
Hi,

When can we expect the new release with 5 tab items? 

Eagerly waiting :)

Thanks in Advance

**Comment by mariomurrent-softwaresolutions** [comment]
Whats currently the maximum number of items? 3 or 4?

**Comment by malvikiran** [comment]
@mariomurrent-softwaresolutions  - Currently it is 3

**Comment by mariomurrent-softwaresolutions** [comment]
> @mariomurrent-softwaresolutions - Currently it is 3

Hopefully there will be a new version soon :) - anyway, awesome job with this tab bar

**Comment by malvikiran** [comment]
@mariomurrent-softwaresolutions Thanks

**Comment by tontact** [comment]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module react-native-tab-bar-interaction from /Users/Ton/Desktop/Internship/navigationDemo/App1.js: Module react-native-tab-bar-interaction does not exist in the Haste module map

I have this problem anybody can solve it.( My react native version 3) or this library cannot support in version 3

**Comment by tontact** [comment]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native-tab-bar-interaction` from `/Users/Ton/Desktop/Internship/navigationDemo/App1.js`: Module `react-native-tab-bar-interaction` does not exist in the Haste module map This might be related to https://github.com/facebook/react-native/issues/4968 
I have this problem anybody can solve it.( My react native version 3) or this library cannot support in version 3

**Comment by mrmurphy** [comment]
@tontact a new issue would be a better place to ask. The readme needs to be updated, you need to update your code to use the module name "@mindinventory/react-native-tab-bar-interaction"

**Comment by longnk-1447** [comment]
@mrmurphy I cannot import  ScrollView, FlatList, after import navBar not transparent?

**Comment by longnk-1447** [comment]
![Simulator Screen Shot - iPhone X - 2019-10-09 at 16 13 23](https://user-images.githubusercontent.com/30386318/66468080-c2ce7f00-eaaf-11e9-9e6c-4a85068be0ea.png)

**Comment by longnk-1447** [comment]
```js

**Comment by malvikiran** [comment]
@longnk-1447 this different issue and it is not related to this thread. Can you pls create it seperate?

**Comment by ankits47b** [comment]
> will be available in next version.

When you release next version? I am really excited to use this but I have 5 tab....
