### ISSUE TITLE
Can I use this plugin with React Navigation createBottomTabNavigator?

### ISSUE THREAD

**Issue by fouad1994** [Mindinventory/react-native-tabbar-interaction#9]
I need to change the default createBottomTabNavigator design to this plugin can I do that?

**Comment by PareshSolankiMI** [comment]
Yes

**Comment by damienkilgannon** [comment]
Anyone have any example implementations of this?

**Comment by timothyspengler** [comment]
> Anyone have any example implementations of this?

In your createBottomTabNavigator add tabBarComponent: props => ( /*the component*/),

**Comment by HarshitMadhav** [comment]
@timothyspengler Can you please share an example code or a gist?

**Comment by fr3fou** [comment]
any example?

**Comment by chetankotkar** [comment]
Any Example ?

**Comment by akashmi** [comment]
We have updated lib. and also added an example for the same.
Please refer to it, and raise a new issue if you are getting any errors.

**Comment by emil-malmgaard-rasmussen** [comment]
Has the example been removed? I can't seem to find a example for how to integrate this library with ReactNavigation.

in regards to @timothyspengler answer, then its correct you can style the tabBar with props, but there is no way to supply the ``` {...props} ``` to the Tabbar component, leaving no option to navigate to the other Tab.Screen from Tab.Navigator

**Comment by akashmi** [comment]
@emil-malmgaard-rasmussenplease go thru the below link for the use case.
https://github.com/Mindinventory/react-native-tabbar-interaction#usage
